### ISSUE TITLE
Broken on newer Sanity Studio

### ISSUE THREAD

**Issue by runeb** [rexxars/sanity-graphql-schema#3]
Trying the example from the README:

```
import createSchema from 'part:@sanity/base/schema-creator'
import { fromGQL, graphql } from 'sanity-graphql-schema'

const schema = graphql`
  type Author implements Document {
    name: String!
    profileImage: Image
  }

  type BlogPost implements Document {
    title: String!
    slug: Slug
    body: Text
    leadImage: CaptionedImage
    tags: [String!]! @display(layout: "tags")
    author: Author!
  }

  type CaptionedImage implements Image {
    caption: String!
  }
`

export default createSchema({
  name: 'default',
  types: fromGQL(schema)
})
```

Crashes studio with console error:

```
console errors
"Syntax Error: Cannot parse the unexpected character "."."
```

Package | Version
------------ | -------------
@sanity/cli|1.149.13 (latest: 1.149.19)
@sanity/base|1.149.19 (up to date)
@sanity/cli|1.149.19 (up to date)
@sanity/code-input|1.149.16 (up to date)
@sanity/color-input|1.149.16 (up to date)
@sanity/components|1.149.19 (up to date)
@sanity/core|1.149.19 (up to date)
@sanity/dashboard|1.149.19 (up to date)
@sanity/default-layout|1.149.19 (up to date)
@sanity/default-login|1.149.18 (up to date)
@sanity/desk-tool|1.149.19 (up to date)
@sanity/production-preview|1.149.0 (up to date)
@sanity/vision|1.149.16 (up to date)

**Comment by rexxars** [comment]
Is there a stack trace or anything? I don't understand where the `.` character appears?

**Comment by runeb** [comment]
```
GraphQLError {message: "Syntax Error: Cannot parse the unexpected character ".".", locations: Array(1), path: undefined, nodes: undefined, source: Source, …}locations: [{…}]message: "Syntax Error: Cannot parse the unexpected character "."."extensions: undefinednodes: undefinedoriginalError: undefinedpath: undefinedpositions: [4368]source: Source {body: "↵  directive @display(title: String, icon: String,…Image implements Image {↵    caption: String!↵  }", name: "GraphQL request", locationOffset: {…}}stack: "GraphQLError: Syntax Error: Cannot parse the unexpected character ".".↵    at syntaxError (http://localhost:3333/static/js/app.bundle.js:93088:10)↵    at readToken (http://localhost:3333/static/js/app.bundle.js:93461:38)↵    at Object.lookahead (http://localhost:3333/static/js/app.bundle.js:93245:43)↵    at Object.advanceLexer [as advance] (http://localhost:3333/static/js/app.bundle.js:93235:33)↵    at Parser.expectToken (http://localhost:3333/static/js/app.bundle.js:68936:19)↵    at Parser.parseName (http://localhost:3333/static/js/app.bundle.js:67631:22)↵    at Parser.parseScalarTypeDefinition (http://localhost:3333/static/js/app.bundle.js:68311:21)↵    at Parser.parseTypeSystemDefinition (http://localhost:3333/static/js/app.bundle.js:68230:23)↵    at Parser.parseDefinition (http://localhost:3333/static/js/app.bundle.js:67683:23)↵    at Parser.many (http://localhost:3333/static/js/app.bundle.js:69055:26)"__proto__: Error
```

**Comment by runeb** [comment]
GraphQLError {message: "Syntax Error: Cannot parse the unexpected character ".".", locations: Array(1), path: undefined, nodes: undefined, source: Source, …}locations: [{…}]message: "Syntax Error: Cannot parse the unexpected character "."."extensions: undefinednodes: undefinedoriginalError: undefinedpath: undefinedpositions: [4368]source: Source {body: "↵  directive @display(title: String, icon: String,…Image implements Image {↵    caption: String!↵  }", name: "GraphQL request", locationOffset: {…}}stack: "GraphQLError: Syntax Error: Cannot parse the unexpected character ".".↵    at syntaxError (http://localhost:3333/static/js/app.bundle.js:93088:10)↵    at readToken (http://localhost:3333/static/js/app.bundle.js:93461:38)↵    at Object.lookahead (http://localhost:3333/static/js/app.bundle.js:93245:43)↵    at Object.advanceLexer [as advance] (http://localhost:3333/static/js/app.bundle.js:93235:33)↵    at Parser.expectToken (http://localhost:3333/static/js/app.bundle.js:68936:19)↵    at Parser.parseName (http://localhost:3333/static/js/app.bundle.js:67631:22)↵    at Parser.parseScalarTypeDefinition (http://localhost:3333/static/js/app.bundle.js:68311:21)↵    at Parser.parseTypeSystemDefinition (http://localhost:3333/static/js/app.bundle.js:68230:23)↵    at Parser.parseDefinition (http://localhost:3333/static/js/app.bundle.js:67683:23)↵    at Parser.many (http://localhost:3333/static/js/app.bundle.js:69055:26)"__proto__: Error

<img width="1680" alt="Skjermbilde 2020-08-14 kl  13 31 53" src="https://user-images.githubusercontent.com/38528/90245211-863b8480-de32-11ea-9e6f-328ed2440b7b.png">

**Comment by runeb** [comment]
The exact same schema works fine when pasted into https://rexxars.github.io/sanity-graphql-schema/, so unsure whats going on here.
